import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, extname } from "node:path";
import { homedir } from "node:os";

// ── Paths ──
const GLOBAL_DIR = join(homedir(), ".pi", "agent", "memory");
const PROJ_DIR = () => join(process.cwd(), ".pi", "memory");

type Tier = "global" | "project";
function dir(t: Tier) { return t === "global" ? GLOBAL_DIR : PROJ_DIR(); }
function cerebrum(t: Tier) { return join(dir(t), "cerebrum.md"); }
function scratch(t: Tier) { return join(dir(t), "scratch.md"); }
function dailyDir(t: Tier) { return join(dir(t), "daily"); }
function anatomy() { return join(PROJ_DIR(), "anatomy.md"); }
function buglog() { return join(PROJ_DIR(), "buglog.json"); }

function today() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
}
function now() {
  const d = new Date();
  return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}:${String(d.getSeconds()).padStart(2,"0")}`;
}
function ensure(t: Tier) { const d = dir(t); mkdirSync(d, { recursive: true }); mkdirSync(dailyDir(t), { recursive: true }); }
function rf(p: string): string { try { return readFileSync(p, "utf-8"); } catch { return ""; } }
function wf(p: string, c: string) { mkdirSync(join(p, ".."), { recursive: true }); writeFileSync(p, c); }
function rj<T>(p: string, fb: T): T { try { return JSON.parse(readFileSync(p, "utf-8")); } catch { return fb; } }
function wj(p: string, d: unknown) { mkdirSync(join(p, ".."), { recursive: true }); writeFileSync(p, JSON.stringify(d, null, 2)); }
function dailyFile(t: Tier, d?: string) { return join(dailyDir(t), `${d || today()}.md`); }

// ── Templates ──
function cerebrumTpl(): string {
  return `# Cerebrum — Agent Memory\n> Auto-generated by lntrx-memory.\n\n## Preferences\n\n## Conventions\n\n## Decisions\n\n## Corrections\n`;
}
function anatomyTpl(): string { return "# Anatomy — Project Map\n> Run /memory scan.\n"; }
function scratchTpl(): string { return "# Scratchpad\n> /memory scratch add <item>\n\n"; }

// ── Staleness ──
function daysSince(ds: string): number { const d = new Date(ds); return isNaN(d.getTime()) ? Infinity : (Date.now() - d.getTime()) / 86400000; }
function markStale(c: string): string {
  return c.split("\n").map((l) => {
    const m = l.match(/^- \[(\d{4}-\d{2}-\d{2})\]/);
    if (m && daysSince(m[1]) > 90 && !l.includes("⚠️ stale")) return l.replace(/^- \[/, "- ⚠️ stale [");
    if (m && daysSince(m[1]) <= 90 && l.includes("⚠️ stale")) return l.replace("⚠️ stale ", "");
    return l;
  }).join("\n");
}

// ── Anatomy scanner ──
const CODE = new Set([".ts",".tsx",".js",".jsx",".py",".go",".rs",".c",".h",".cpp",".lua",".md",".json",".yaml",".toml"]);
const IGNORE = new Set([".git","node_modules",".lntrx",".pi",".wolf","dist","build","__pycache__",".next","target"]);
function scanAnatomy(root: string): string {
  const entries: { path: string; ext: string; tokens: number }[] = [];
  function walk(d: string) { try { for (const f of readdirSync(d)) { if (IGNORE.has(f) || f.startsWith(".")) continue;
    const full = join(d, f); const st = statSync(full);
    if (st.isDirectory()) { walk(full); continue; }
    const ext = extname(f).toLowerCase(); if (!CODE.has(ext)) continue;
    entries.push({ path: relative(root, full), ext, tokens: Math.max(1, Math.ceil(st.size / 4)) });
  }} catch {} }
  walk(root);
  const g = new Map<string, string[]>();
  for (const e of entries) { let v = g.get(e.ext); if (!v) { v = []; g.set(e.ext, v); } v.push(`\`${e.path}\``); }
  const lines = ["# Anatomy", "", `> ${entries.length} files · ${entries.reduce((s,e)=>s+e.tokens,0).toLocaleString()} est. tokens`, "> /memory scan", ""];
  for (const [ext, paths] of [...g].sort()) { lines.push(`## ${ext}`, ...paths, ""); }
  return lines.join("\n");
}

// ── Scratchpad ──
function scratchList(t: Tier): string[] { return rf(scratch(t)).split("\n").filter((l) => l.match(/^- \[[ x]\] /)); }
function scratchAdd(t: Tier, item: string) { wf(scratch(t), (rf(scratch(t)) || scratchTpl()).trimEnd() + `\n- [ ] ${item}\n`); }
function scratchToggle(t: Tier, idx: number) {
  const lines = rf(scratch(t)).split("\n"); let ci = 0;
  for (let i = 0; i < lines.length; i++) { if (ci === idx && lines[i].match(/^- \[[ x]\] /)) { lines[i] = lines[i].startsWith("- [ ] ") ? lines[i].replace("- [ ] ", "- [x] ") : lines[i].replace("- [x] ", "- [ ] "); break; } ci++; }
  wf(scratch(t), lines.join("\n"));
}

// ── Daily log ──
function dailyAppend(t: Tier, text: string) {
  const f = dailyFile(t); wf(f, (rf(f) || `# Daily Log — ${today()}\n\n`) + `[${now()}] ${text}\n`);
}
function dailyRead(t: Tier, date?: string): string { return rf(dailyFile(t, date)) || "(no entries)"; }

// ── Learning ──
function learn(t: Tier, category: string, text: string) {
  const section = { preference: "Preferences", convention: "Conventions", decision: "Decisions", bug: "Corrections" }[category] || "Conventions";
  const lines = rf(cerebrum(t)).split("\n");
  const si = lines.findIndex((l) => l.startsWith(`## ${section}`));
  const entry = `- [${today()}] ${text}`;
  if (si >= 0) lines.splice(si + 2, 0, entry); else lines.push(`\n## ${section}\n\n${entry}\n`);
  wf(cerebrum(t), lines.join("\n"));
}

// ── Correction detection ──
let lastAsst = "";
function isCorrection(t: string): boolean {
  return /\b(no|nein|falsch|wrong|incorrect|don'?t|nicht|stop)\b.*\b(use|do|nimm|mach|try|versuch|should|solltest)\b/i.test(t)
    || /\b(actually|eigentlich|rather|vielmehr|stattdessen|instead)\b/i.test(t);
}

// ── Extension ──
export default function (pi: ExtensionAPI) {
  let injected = false;
  const tiers: Tier[] = ["global", "project"];
  for (const t of tiers) {
    ensure(t);
    if (!rf(cerebrum(t))) wf(cerebrum(t), cerebrumTpl());
    if (!rf(scratch(t))) wf(scratch(t), scratchTpl());
    const c = rf(cerebrum(t)), u = markStale(c); if (u !== c) wf(cerebrum(t), u);
  }
  // Project-only files
  ensure("project");
  if (!rf(anatomy())) wf(anatomy(), anatomyTpl());
  if (!rj(buglog(), null)) wj(buglog(), { bugs: [] });

  // ── Session-start: inject memory + daily summary reminder ──
  pi.on("session_start", async () => {
    if (injected) return; injected = true;

    const parts: string[] = [];
    for (const t of tiers) {
      const c = rf(cerebrum(t)).trim();
      const s = scratchList(t);
      const d = dailyRead(t);
      // Tight injection: extract only what's essential
      const dnr = c.split("\n").filter((l) => l.match(/^- \[.*?(Correction|⚠️ stale)/));
      const prefs = c.split("\n").filter((l) => l.match(/^- \[/) && !l.match(/Correction|⚠️ stale/)).slice(0, 5);
      if (prefs.length) parts.push(`## ${t === "global" ? "Global" : "Project"} Key Facts\n${prefs.join("\n")}`);
      if (dnr.length) parts.push(`## Do-Not-Repeat\n${dnr.join("\n")}`);
      if (s.length) parts.push(`## Scratchpad (open)\n${s.join("\n")}`);
      if (d !== "(no entries)") parts.push(`## Today\n${d.slice(-500)}`);
    }

    if (parts.length > 0) {
      pi.sendMessage({ customType: "lntrx-memory-context", content: parts.join("\n\n"), display: false });
    }

    // Remind to summarize yesterday if needed
    const yday = new Date(Date.now() - 86400000);
    const yd = `${yday.getFullYear()}-${String(yday.getMonth()+1).padStart(2,"0")}-${String(yday.getDate()).padStart(2,"0")}`;
    const rawYesterday = dailyRead("project", yd);
    if (rawYesterday !== "(no entries)" && !rawYesterday.includes("Today built") && !rawYesterday.includes("worked on")) {
      pi.sendMessage({
        customType: "lntrx-memory-reminder",
        content: `The daily log for ${yd} has raw entries that need summarizing. Call /memory daily-summarize to consolidate.`,
        display: false,
      });
    }
  });

  // ── Session-end: inject daily summary task ──
  pi.on("session_shutdown", async () => {
    // Write a raw marker so daily-summarize knows there's work to consolidate
    dailyAppend("project", "Session completed — call /memory daily-summarize in the next session");
  });

  // ── Correction detection ──
  pi.on("message_end", async (e) => {
    if (e.message.role !== "assistant") return;
    const c = e.message.content;
    lastAsst = typeof c === "string" ? c.slice(-500) : Array.isArray(c) ? c.filter((p: any) => p?.type === "text").map((p: any) => p.text).join(" ") : "";
  });
  pi.on("message_start", async (e) => {
    if (e.message.role !== "user" || !lastAsst) return;
    const t = typeof e.message.content === "string" ? e.message.content : Array.isArray(e.message.content) ? e.message.content.filter((p: any) => p?.type === "text").map((p: any) => p.text).join(" ") : "";
    if (isCorrection(t)) learn("project", "bug", `Correction: ${t.replace(/\n/g, " ").slice(0, 200)}`);
  });

  // ── /memory command ──
  pi.registerCommand("memory", {
    description: "Memory: show|learn|forget|scan|bug|scratch|daily [global|project]",
    handler: async (args, ctx) => {
      const [sub, ...rest] = args.trim().split(/\s+/);
      const txt = rest.join(" ");
      const tier: Tier = rest[rest.length - 1] === "global" ? "global" : "project";

      if (!sub || sub === "show") { pi.sendMessage({ customType: "memory", content: `**Global:**\n${rf(cerebrum("global"))}\n\n**Project:**\n${rf(cerebrum("project"))}`, display: true }); return; }
      if (sub === "learn") { if (!txt) { ctx.ui.notify("/memory learn <text> [global|project]", "warning"); return; } learn(tier, "convention", txt); ctx.ui.notify(`Learned (${tier}).`, "success"); return; }
      if (sub === "forget") { if (!txt) { ctx.ui.notify("/memory forget <pattern> [global|project]", "warning"); return; } wf(cerebrum(tier), rf(cerebrum(tier)).split("\n").filter((l) => !l.toLowerCase().includes(txt.toLowerCase())).join("\n")); ctx.ui.notify(`Forgot "${txt}" (${tier}).`, "success"); return; }
      if (sub === "scan") { ctx.ui.notify("Scanning...", "info"); wf(anatomy(), scanAnatomy(process.cwd())); ctx.ui.notify("Anatomy updated.", "success"); return; }
      if (sub === "bug") { const bl = rj<{ bugs: any[] }>(buglog(), { bugs: [] }); pi.sendMessage({ customType: "memory", content: bl.bugs.length ? `**Bugs:**\n${bl.bugs.map((b: any,i: number) => `${i+1}. ${b.error||b.message} → ${b.fix||"?"}`).join("\n")}` : "No bugs.", display: true }); return; }
      if (sub === "scratch") { if (!txt) { pi.sendMessage({ customType: "memory", content: `**Scratchpad:**\n${scratchList(tier).join("\n") || "(empty)"}`, display: true }); return; } if (txt.startsWith("add ")) { scratchAdd(tier, txt.slice(4)); ctx.ui.notify("Added.", "success"); } else { ctx.ui.notify("/memory scratch add <item> [global|project]", "info"); } return; }
      if (sub === "daily") {
        const date = rest[0]?.match(/^\d{4}-\d{2}-\d{2}$/) ? rest[0] : today();
        pi.sendMessage({ customType: "memory", content: `**Daily — ${date}:**\n${dailyRead(tier, date)}`, display: true });
        return;
      }
      if (sub === "daily-summarize") {
        const raw = dailyRead(tier, today());
        pi.sendMessage({ customType: "memory", content: `Summarize today's work into a clean daily log entry. Read the current log below, consolidate into a narrative of accomplishments, and rewrite with /memory rewrite-daily:\n\n${raw}`, display: true });
        return;
      }
      if (sub === "rewrite-daily") {
        if (!txt) { ctx.ui.notify("/memory rewrite-daily <summary>", "warning"); return; }
        wf(dailyFile(tier), `# Daily Log — ${today()}\n\n${txt}`);
        ctx.ui.notify("Daily log rewritten.", "success");
        return;
      }
      ctx.ui.notify("/memory show|learn|forget|scan|bug|scratch|daily|daily-summarize [global|project]", "info");
    },
  });

  // ── Tools ──
  pi.registerTool({
    name: "lntrx_memory_learn", label: "Learn",
    description: "Save a learning to cross-session memory",
    promptSnippet: "Record what you just learned",
    parameters: Type.Object({ category: Type.String({ description: "preference, convention, decision, or bug" }), text: Type.String({ description: "[Context] → [What you learned]" }) }),
    async execute(_id, p) { learn("project", p.category, p.text); return { content: [{ type: "text", text: `Saved.` }] }; },
  });

  pi.registerTool({
    name: "lntrx_memory_search", label: "Search Memory",
    description: "Search agent memory: cerebrum, buglog, or anatomy",
    promptSnippet: "Check memory before implementing",
    parameters: Type.Object({ query: Type.String({}), source: Type.String({ description: "cerebrum, buglog, or anatomy" }) }),
    async execute(_id, p) {
      let content = "";
      if (p.source === "cerebrum") content = rf(cerebrum("project")) + "\n" + rf(cerebrum("global"));
      else if (p.source === "buglog") content = JSON.stringify(rj(buglog(), { bugs: [] }), null, 2);
      else if (p.source === "anatomy") content = rf(anatomy());
      else return { content: [{ type: "text", text: `Unknown source. Use cerebrum, buglog, or anatomy.` }], isError: true };
      const hits = content.split("\n").filter((l) => l.toLowerCase().includes(p.query.toLowerCase()));
      return { content: [{ type: "text", text: hits.length ? `**${hits.length} matches:**\n${hits.slice(0, 20).join("\n")}` : "No matches." }] };
    },
  });
}
